apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jupyterhub.yaml
  - jupyterhub-host-ipc-sa.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: jupyterhub-custom-cfg
  files:
    - configs/jupyterhub_config.py
