apiVersion: v1
kind: Secret
metadata:
    name: thriftserver-server-conf
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    thrift-server.conf: ENC[AES256_GCM,data:Zc5hmNsmrNjODKajcQCyEDu/K0jCj2OeQQiRc45semNArKrzAU476a0WB9WilihsO2dzeJj5YRKPIxwz05sRoiGFbyZzrORaVroR3oqBFI5wOnj6GbTR1SahXRRxvr37Rq2lREg0+w8SyrvsZ4b4Of2peMFGN5VaQehy3/r1jNTaQsCHPMMNopL4QjNCnyXaeDd0CpgXfpkxsi0k8EO+riQ1PM1JoZPndtB+lQdoLc6Gh1mUhnXCjxTYNWyEzoCHvnDlFKt9cQxrARtHkK39Cq1QHke/4IlDH5R9L3B+/6nqnvDA/CQwIuEesqI0ih2jgw9PoDgK8yW4JExi+1pupKXMNhxObeMZHND1o5z0ALKZoSHexdgLP7W/GinznNEogRjCktYXRREoRWFlQYkYwk/1l+FhlmSz9vGIFLlyTtvtniFZsxJlvAcHrnWGdyBbUWdHk4O6Tnv+IsLCTdSTkjujmXrxAGK2tFzSZ+hLUyXrM9+hwIGsBWdUmc06/GzAmRYi1HCOpn276USoymrblGyG33+FyI92KxBbx7xw/yNV6oRDb4qM4ExyaU1AjlzIWvwHVzYJmoPhxe0WkSYJJKiTT9XZU0mmsIk8gDN5LJMKPxk4EoAmEA8lRrT9YEp9vcg/JTnSr/RL1lWuJbBpYWQybK0WZyQxtCRTmVr1XRAwOrwgj/fesDtlOpKaTdda98Z5743vcX0aWmkRHQKgLHp6eHfswWLcZGZi7NmBMfi+Tc0CCkMAS4bv3kbz7eMKiRMJjIszx4lf9f/15DigjGFkM6y/+wLDwlX3eBE6ujeeDJMQUFJRcS2dE7WgyIhKHSHjXKJyA6euA0ZMqhYho072RIw7nDv6Pg0PxmTsChJnyp6bGcSwcrPl18/QnOqzsBK5JqrfWH5oRuGiHFgeUS36GEbBwXRVRX6LiJhSiVurYipS5la7mWZt9C0WAV73yWQKcR0ZDfG47vGzDV5AOVu5cUdhEJhBY8Xk3eTdQTzMKAojlCvHElTN5NULotjkSXXD78QV61lC7tpsPtaqbzKo7EfR3iiJPRgQ/8WpXydfXj5hZQM7IjPUgkFYXc13HNHinAv43b4LJ0v7rEF3kAhBFR+wSMCpzwIgDfCZcXkW8jis6KdrsJloj5WGp0ODNjBl2mocTV/SHeIhVTPH9hLoHtjNIijVOXwD7Cjj4DmvIclZFaBrFTVML9UpcU4Wi02GOeVC/S8ynmkN3TuCgVW1s7hblt9hkwocQZaQ0wS0U8hMgHGLwOGorMhkYFcZvCPSh4YOsPbsZw==,iv:UjLStwlHXZOkbAiluHeIACTyJeJMmpOc/mANnXw4M3Y=,tag:QEcnfFI+YZyHqss/7Hp4JA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-17T15:00:55Z'
    mac: ENC[AES256_GCM,data:mKkBQXhqkNbgek/VheQmd2xSkfvlWLb0+O6zp5n9dodi57CXqvWA8hpyWjPPq/+CzjAqh7pjtegIh7jyyyvqQmUJEb2sUgAGq3Bphad+WPScmZ9PbVnoCAsWcM9jTfbKySl321eoyAUmXoCh6OyZHiVIcVYBtFS8HUYkdj5QHes=,iv:GIFiTkD9bF1hIOd6lEUEyFGW6sl57pxMIWKsBV2L5Ro=,tag:B+frmmNftYrgvOmgjdN/4Q==,type:str]
    pgp:
    -   created_at: '2020-12-17T15:00:49Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf/W/eVhREM39cKbTy6sY9xVo50bTta11nWSupeVhLfx19I
            6YJyGG+dfFugGYJ01U2daHiSIOHP8PvdEnPp70esnMdFedOq1kUe3UvEQ4Djt+SJ
            A453U6DbzbbhScxI+LlAF3VEpbFfAb4fQ5Lz45vi0jHTv42pLVaWvYT8lmZ5z5E/
            Cx0bZCFSvBI0yyiqbqQiGjhcWOO3Z/xiyURz+XqLh/aJutsaRXyKnRh54dc6hdv1
            rEiNAWajJ3jzsfusPOArx5DixYEP7NW0TPDbCtu5BuD104wBh3Y+svgRqcCwgVMU
            98Eyi62rqXni9V1CCOfeFoSnaHx+DQxvWrpXsohHGdJeASxPF1HjY9KFXHH0SclD
            AkLRV5KpyUxaVNt/1t56y3BAyhIpTRJ+DTIv5sgXPy9jJ/qQjG5kR8n1ltEn/w0Z
            kBY4eJJxSZM8UN7eZ3dpKiPm2/htbWdhLIrGJWZlsQ==
            =9ogJ
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
