apiVersion: v1
kind: Secret
metadata:
    name: thriftserver-server-conf
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    thrift-server.conf: ENC[AES256_GCM,data:yYaKACqWW2lL+/ugXd6hl9AlyDgithrGLODzwYE4TyMucrsklrlEaMlS22InFkHpDyq58Oox3t8fKcmhwoJfLFQCHmZBjW9GXoFOXvUJg+IiXAPg+jdbHfGBnw3YkBhB6wSuXgLTqOvilD7WawyrF01MxzaDXdahnJsidCyfK9OsL9ofvaZNR7KmlBm1dDjwz+7sgox2IIayNlXLlhWvYRgMzFHszDwxk6hZPVCEc3RXRpFxSPn5wyIGhyRt43q4dQ2eMlS36z+O2t4RW/UGY33b2IUjBHqjCROdjhB6kkt2M71d9eETq5EulZU7PBFP9MV7VuehQhoz+7At5P3YDoMP7E2LEx73jW0R8W//fZtiRH5SHFkhh1IWZQRBOdgKktVen6ZlsgSB5bq/Nj6yok4mgRALQQEQS71iUWaERrdS0FVWA4JHH1qRpjAoyFU5Q1crSny4swqWlTJ+XASv/qmbn7sOaOv4uFFjw8z9Mw+I0rMcYBPM2+WdPZip9gdUQdFoVdOXhXl/uMOYOO1yGvnnB/h+2a/x/Dwb54SpdeeoGMY9O/nTGJwEH26lbwGlRhbgY9018WVBSUdisjYRVTiL/ubzBXOWtpBcK7tWkCW50Al6bFizbJmo9A/YSrOk5KstoAy8FhW7Fp8Uqf+mZxOLZvjTXWJRbHCsHiytyq0fcYxKW4DZkXo8QiDWTJ+rxiMnmt8FwCApS6l/ZbSjHkNuDzk4AfoxpuzkYpM7xQx1A+BrkGlvJ0p3SEgRnG17ayBwCwOXcuAy9L2BSjdJ9f/E2vc89eW453WvT+HjmWeesmuWhE9JaL9eaHVCxDUBp+UWGGTAGFu6nBrwU/I/ckFZlIfPEDLqkVJDtpv81mpUbWI7MkxOGHlQAyziJ+Xm8AhVjCRZo7c3Rh9L76DFAwoQDzQCkYmLBajfNeXXeCOJMzcNTnI/PTVpueQ5BjsSZ0R2VF6oXdMYcxtbAxyBmm6/r0pagBOWSSK4+lOrGFrF1obRt1hVTvHXH7ku3+527xLWaMU0mCuls0agENwNum12j+dw41/TiOcHNbkxdN7N8gZ7WlomsAmjGYvWp0sGBkru5YqnBzJk5ue2yE6ng8IngPFvUjcX2RfN7vdd/ja0J8OPWSp7ID4v6hKnJbVJ64Xmj1u4N+5+qaDwpUjveyzL+cgOEXq5fLQeKznye1dGjqxwOMbxWTFiB4Mvc6v7jpE9gP8/TjQhQlonnKVacfBIllzjqFcHYdl99BMsmRN1c9J7v9I49Avym7MZOSNNdL9neiUdQC9Bv68=,iv:SNZzdFfJuMjlyqyfsJLsEBARGG4TNMHLupp1gbJE408=,tag:Vof9UUqk6SiS0308NGDNgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-22T14:29:03Z'
    mac: ENC[AES256_GCM,data:OXy/7jcdGxfUamU5RPfbtnkJEB4FEBCUJRHMtXrTULe63CKhn5UP5N+ZNQogIpztD+xm9Zn+iOUXH0T8M6ONM/FwRvaeECsjZTsLmPcbBLESad4LXOyHDF6GzHqfKWgPaJMrPAWoLBMJAoIcq5tGUXKwcjpprWmq61iZJno3rHQ=,iv:9iyjHLc3xf8MhTup8jDV5+FBFlHv2MBNB363HCdVQpQ=,tag:E4C9O7JYa7FqHtoVVfBpnQ==,type:str]
    pgp:
    -   created_at: '2020-12-22T14:29:03Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQgAmTQgymbSXSW3xZBsXou7Ij9GrYMhz6e60MNgKttF2690
            4PRamimWEU+xc108ZnVm3H0GoOOJiHplM2fo4Lrkp9aCUt62ePrnvMpAoHoXCVk3
            Wx0d/qpJOEmJzBbEDTGSHrjqj8aPICVdzFhQh6EvzgX5NuAVYT6sEh5zLM9b4Q4N
            ETM5fEoLWp8bB5AwbeMze/XuzXAI78PGp9Fph1zyymcLCLCXbzAl96tFklqJKGte
            kIAXNgzIzjAHY4Vv5ftw2tPZmiR6cKJXmaSw7NC/Vl80kmcKqyNinMDM77IJSsIR
            Ey7yPgNsKJol96IS3La8LGFX/rBZlPrbCmDfrQXBGNJeAYrI82G0lty8lPN8FoWh
            /2TuNV1oIOFFOYD4g64C7sjE8Cp5DoN62G6vHIreiW19uy/ZsvDt58/WCCKoJG/E
            hsWBlEB23UwPA5X+L9JwK2c3g7R75S74vVovmHh6gw==
            =/f9d
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
