apiVersion: v1
kind: Secret
metadata:
    name: thriftserver-server-conf
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    thrift-server.conf: ENC[AES256_GCM,data:huO813JDNmE+kpTYakJZfRLos3n0POZzi+cb6RyeP793BIHznLtVH3LIjOzNdJ0Gurf0Nvw71HOo6kRsa55Vfs/uPoOlrWm/Pt9uI+P+FxOG7+fgwKr32B83V+YlNORkDTOvFbpIL2/ynPh7zFm0XiOBommFNdBfVBI9c8tobCKupo97JxU7sC8Tw/g+lcrt+r0ZGeNkGW5NLGacnCAJBYynghTKRd5TMD+0HgG+lXKHZrbVZA6c2BQXMOklbZylqFy1+4mangrC9gvFZfNUrEdD/bI98OL4zRhRPeBMYT08VVXM+o9605wRzE1fEzaaoCeebqtOmO6G1YysLn14CNV8byg4dqCsEM6v5a+UsxfY11A9NlFS/r+cj0/lCX+gIQkmgyeF248ZrNLHHiXtpOBFhOumAE3/xGybyHd8jImvdZa09jaJHOf/8q2K3NaUMkIyQbwy/MtdqYnkQ3p5xplzjqJ7LIOP2RhJF7IVfnbm9g3Jo5kM0LWoxsrgV6a+4KDAGsSPq+pTmEIf0uzA46iB95BG3zwBqZsKWKeBQZuLJY31GYtiz/UFB3/k+vFFkI7Yd05AYUSAoS9WqllIsAe3GUvBysW1KcDCTFtf0+tMLUo4HIdLTd6yAg5ohAChS6j20Q483yPdEitmwWBTqlEe/QWPIQSGzZTdxYvE0MUn51xOnU6buKquA4cemEcGzoadr/R0Frgm3+lRY7pbYNjQ7UbCP6QdqAWm0lpP1VzCnKjeCAKlmq+yRB+r9UnbFPtbHznbgAxT+hMD8EPtVSz5PFApnqXiT5eCa56LZZvHdMG9qRge4q9972hLHeA5GAcGoKzMi+XvKwFqEKACOm36aXMF9M7f7zg0BEMsQsso6YKvv5oQsd9YrzNyyTRw02I3ZlP5jW5pTLDWg6UaA8FJN6MTYOqasOzvhNdt4Dux4kKFG0LyPKh9KeMZvSagMOYhQgw4mhs6M/fTTSz4YrUHI+NSebaHlfKw1bGybPK1phIVEAr1bKVtSuRtrWX2jIzN2mmgKt/F2llah26uU2jHrTJR/bIDPIHpz+F6xH07ag9uPbHXul+7l9fWKk/z7ZcKKngXFzcMimKi4qvHxuWoUgf97zF2/u0FyKjmh8CYHGhdRGPHBqqkf6lVbHpJL7cnOngxLIe2B0+BVNDONREpCwV3GncIcsgUum34HB7X1kCT+ZhSOTTCD2tzjb858lXy7hGvBRd01z7F/4FFi8cmeZN7vReWxmaUA96cUiX33jTY4pVLxdf23EvWMYZovmMGCaOSoWciyIWKJOJ5BepZsgYgam4p6RnC2e8lqfjFQ3oq59ygbEBTMyfTyxiv+xRDk4Y27bgQmfvm/aGcXxaIUc9Grw/EoZ8PuAXzVow4dlkRNP3F9j6nQZc/pbHAWoqG8d5QpNbBBEprCJnuT0ABtYhuxAWn84BO0Fq8aLsBvBstx7CnOphUJ4jWI+iiiGBKjWMZtCOZ3Vtu1CmKeYXZFtV/VJqMsSCD/7GNsiu1IXwV1rMuNXNktQS36K0EFBfBKn7kiiWcw4Xth1Jnev6bSQS0ke/bjyPamidgnsQtGbZJoMxrsijsI30sl4sDll0iThCPopdpxVPNenx7WxPmxmooG1w7pa9cHDc3hbXhihyHHdC0VQWOjABG/Qs5B4C7M2hzueXalzNn+IQ6uUvjStIM7g==,iv:e0LpzCqvhpdl1VbzrNQaLStRrjCwEbTYcZSjMG7XcGE=,tag:Jg8s+aHHAPrKkljd+Qv1Sw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-15T15:38:13Z'
    mac: ENC[AES256_GCM,data:7sU26w+x5+7M5Pq7h8kRuowiB4CidkM1BbxORxOFRxerJ8mV4pNJml0LpL5Z5FcWlOimqUHmg2BTGJkYB+ZAFVPOPcH9FQWeg0reQUdgh7zEI89PgQBudRIZk20GAcSAOcvgnNm/mKfnZGcKgqUB007PcPOTYCxXrFAe6iKyGPs=,iv:xCNftYrdc+zhOqwYs6kkSwbMXHWXuLGse6aomhhhV9w=,tag:b0gTymesbkeOtTQN03Dafw==,type:str]
    pgp:
    -   created_at: '2021-03-15T15:38:11Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf/YbOpEOszEzGe/aEayvbO1oNM573Wv3DiDPBE6VtnRfoF
            1EMCfR1w3sOCf51wocYeISOXf1L0zYtJx4p5PmR4f7Lj1F5VYIyu4+iWJqJeyYeS
            65s/M4lFtzF5fbNdNs3J045eaoreBfRRJumgE1Xr5/l/o8iKv0YOrLWHz0TEhPFC
            cbrcpIu5I9vhoUMmcm9xdGB8/fqScMN10MdHoDObM+9rXgAK64PyTsAawEahqrGR
            uSZ+pJCiCg7mDUHrJWMMwx02YJ86Tw1B8FTHqz5By/yNnuVYtH+F5lPbCyXBUMY5
            EsvPoL53OGxI3DZOrNSwNF4OnKUevng/iWSkmrWg1dJeAVVp9y5pan0VpTf3CRQG
            ilYWm0gUnuYxY7kKsATERlfxiS42OtCoRrCwEbTvWCLufnTeKL6bxEsteL0ICYOG
            CzYF+Z/jMFg8oomYRh0cGfvh5J/9mRxjtw/VFG+awQ==
            =KM1H
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
