apiVersion: v1
kind: Secret
metadata:
    name: thriftserver-custom-authenticator
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    DataHubAuthenticator.java: ENC[AES256_GCM,data:sztFop/e+mA1eiG5cFaYFKRxrP2oMVQUzHUhb9EYr0/iuJxZhATpZtA3bGIkt280W4vSwMMAEAXszmT/ZdnjNY7JU6nyd5zipXEl7IXkc56IEuOZfq3O8slFMsQO4sSkqLI32GJ8E8ToayFGe7BTRzbvfqvCdFnqMVTNFBM77TydLRDbeW+YLjHqqagDGcWNgrEyoZWKHEsfDZS/y3lC/B4J7mNaqNky184JY883koTLZVhSRDkT3ndJfiCyNBP324gjFJSubdP1PtcUinrue6CO1ZMNSiQD1uSyrpaRJA8ddLsaaMt1p0UvXWWb3Mq9LnXklWKWBJTzgbb7jCDZjNGmTnx40sXr+hnzX7o5UDLXwdkWdWMVY4K3ZgXqpTpYjn+H4Oua2JeumOdy2j33REpAxWxX8LVwM+3NMewWAti+yNCXE5vZJ8yqsqVRHXUSKiCtWZxzip6/jLAVp1EIMbxXtTKozV0ex1PLsZxAC/yRSghVwY9D9mCByzL/yUnpsQZY/hb/OdyUC1J+mGBywK7G0vZ/Y6aN4fEWxkFU7k0dH4u6OfX8+1FNuc/RCz0gaS62aanJesU2H9hUWzmv1ynMoC8OhoXNYTFDTGRvPR1qsfJs3QVrifj1Uh9SNxAOynzs2peFylikVHmGrOIarab9pBHAQ85wFFGQvs4hQFvbj/K7YbQdERaESouPHEJxzDW9fBvKNr95CBuOG4aXBDGLhef2dHsAppBEFLx4/OILD4hI6JRoLmLjgNvrmWABPi6juLDbPvxISsWrjeaQ/n/qr7zpH2FDR/mL6R/MSCCD7oV5ZBDHzEijfUPo/HfrT3CssLsdPc9DqbJV1uf2wpoDmt9F35pw3XJy9OYXWEoDZFMKrmP4oJIe020O+wd1r5SNGUUKlr9TRj1mUP9RFt+lk/NPB1D4vVPb2xvkc8Iaus2zEILblQluibFDX0k5r/Nvf9gSEco/E5eciUrEU1RTUaV1jLSzPd+0VJz3+MImArxqgXW15zeYebo8Uq1TAQsIDuUIJHqHnvSEWKAzOs/e/XCJog02unCkZpCb8eBVvocF3jybOl3O0hh+9/7maRNq7nfW6Y0rt3HMFQ5zRjF1Zael/dh4GhuvnX56ow0VMruulgVlDq7tZT/U6ukO4WwY6w5DkPVmTDJaXHE7BgynkwslVKGJtMc9dOvI+Qe/jLQt/zdV8vVSw/xOivZqoeE8jc/N+AbN5/UZtGWudfW94yqidWyNrG00DFRIswmZ1PCUCVNQStZ8jZhHYTj8yt7EsdVcTFEsXYkmXlfD0taaTVtPfnqUM/4jRN0HI/bIVQenWaQounruNYI6ZkWaGier73Ran+CmOGi6nn4Iu+a9XCis9PhEK/NtwayFEu7X495Q8CNqQ8VsnDAZc2xsqHw8WawzS5YotwyPNbAR6fv1Bj8=,iv:90gdggpTE4zPCpVqot17Tgn4idDDHZ6G9JFZSyrwsZM=,tag:+jWAVvzxw9nJVHaLVaVgjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-04-13T19:14:20Z'
    mac: ENC[AES256_GCM,data:5RrwBRxxz70N7+V8UvTzld1/uhBVxTY3UOEdVRsImuCdsi5orQRa5CAXjyJKJm5aPHtn2EWyN4UdnM1fC8APAnUPmw8H9UUMyZpYXwfRAARPwHxvs9cBpHjDLvb61O6zCsWaGx3bY5PQWhRA4exn9+OfLOyGX04Jb3QwucWEDN4=,iv:PvXmkuAc490u5P6g873ocE1lO3+KjZffz3Qby69o4/k=,tag:03vflL82lAJjyEqzExPplw==,type:str]
    pgp:
    -   created_at: '2021-03-16T20:27:19Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf/boVxgW/0NzQtko1/t42ZuG7nKYyYVzSnCLB9YWVDBNvj
            qSq2mOTx5q/2Czl6qXA3a3NEn9SLpruL0lOl9eZa6zObrSiEQ33hFPFla0Gxqq6O
            Oq1cbTlEKOc3jjozfvkARk+UfS71NNxMi+gwL9niSfumSbwGFXhcHaOUHZWHVR0T
            tY574FFLrxy//3YpsbPzvhNLdW5cYB2jejMRFlPrPQaEmMrbOFel4U3nJ/MJ5vyc
            R2SBnjjGTYieMccejr4lyziP37v8etQphooj5RYvyOS0fyZ9IwUn0RYf0Ho4B3Md
            wJ2/G6m/F/TRqQ6swjY3xB40nKK/swCUKbkH2w6QktJeAZv8kZhow9uMoiiEC86g
            vKn7Y4D/MEZnVLbIlH0YLoM5Q5UKeSnp2fXBALow45pBFFihAQ94DMs2L6+0ERHw
            D/7UH+7vRFrOFsOaNscnliXKjauPpB+M14mfxv8B8Q==
            =7XdW
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
