apiVersion: v1
kind: Secret
metadata:
    name: thriftserver-custom-authenticator
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    DataHubAuthenticator.java: ENC[AES256_GCM,data:Ds5zTsMz8Rzrw44LtRf/LIG6MbmYTRmHktan0Vj+X1HFKhVNEaDin9BkD4ZQ23phR62unB6W3Tb4vrv/eHm26/+uTkjLu92W2t6ZaOVqP9xbHSO4vGmK+8jytPYbi7Ved0x6EQEN1Y5a1Rj+WdgFSCrDVNmZ+saZOLY5AWwIA0JD8jWv/P0aPlPGMnwo1+U9kBiK3dLxefZa8VNaMn2Pf8DHLRy+aLdZNRV1ROUZ0Xr/TRNxl8FG+ti/R5ZtLsGgzQvKCPlP/EVu3hwwtEpN9oxkZR2jJSZTy7DCakDnXzR/EpRArfOHL74JPmWoYByhOJWbZsLyWDQigC/mWJ2U/r5s+4gixAYpffUdWK2KKuQMSwl7h4km2rR5pYeNoH3kfShY56IdjAY6uqfHmOyEYMxyYZAtde/+KvtwWu4Jq625N3Pva+aZYKY4XPGDnzQLxEW2HYIHvowbmqeJK5NI5sa0NoN04RBcySPLIiuI3ybSUFtIsLyQI+RZWvaQf+2JQXL1Q6uTUOicq2KSzzNa/9Df9MA3PKNjC+kHuOaoIkHcl23LqAQ0I1x5vTgDfiTJ+IzsrQFd0jh2t7PP40p9Gc4BN7wQEt6PiMSKLRbNvaN1VRYdIZ+yzZA5fsSubrrn1XJd/X4dETZeVhV9iqxZI52LYfFRzaCx99AwUsfsgvjp5E7SY7OhpkMNM7KAsVc0N3cRiSpPelzD60Q8y0fWtRtgllsrDCJF4QsF9Xh4J8y2X/vLvGkhXOIIMCX8x/RAfh+uzU02i65Qf5m71QmCe5kddOm3On+G8sbXjU6dJ0oLSwPWNQzH5i4OY/U/zcKQLKBRWpulttoQ0kIGQ5n5T/LfMc5TiS6BAx0evkJ6s4mQPKHPqfJrXA7zPuOQ2ap7X9odiChDg//46+L8DHIst0PCOY9dmcUlc/H73MyJjg8dTc06EOu8LdkSpegHrtdEVblQc1Sgx4a1+A5HBKUxjmRl5WCq6yMbxENoLeJsGDV+tnp+5WPnziI+k1YLGljdWBPCUNwXpD7zI0qDArO6MbQxeWSxinpu2T4NxZJbIK8sEdl/jy32XIQzVfznPW/utjMgs78ePQF40Y9Fi8NrOUBG8VQlqnkGq1GR2ohH+Tmb62Fx72G/QRHtWv9OFEUuvtnn3PiZn0plLanfevHGEiSr1GFbOc3LGKhW+Bt9qNF4/PXEIbhOtAxmk414tyQCMWXsoQQ468GIXRPldX224xcxwlxeiqQvhJ+QU5HV5Q5RZChCzsvSYtyihCuH5H/z1BmskjrXGzLrFYRwFGc0L3IvlE13uN8I6i0IU54pTKkT/hJcv3jXHpAXemo8COl0HFgzWrdvDaE=,iv:0r3LHTjmSrN9WgzMdbJk9Wia1vluIy4yQLc/QajrVtA=,tag:iKun4lj5saRQEP7ZQ7cGeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-22T14:55:14Z'
    mac: ENC[AES256_GCM,data:zpRgKZxcy0/Nvj7nTOEoz9tXpBmtQZwylhStNHEJ0sevaz5bl6IhfVzoV0rJyzA9e06+Q6om1RM9wjtC1QeRxBjI1QbQDaE/70DGuMLloG+v00cgw7mxokVskl3+ixF/7jlCN44rnsTxAni4D/7iveZ0CAzOwkOMxNbQPcTWlU4=,iv:f/0zE5keQwmI/Flf+cCI1QpLOjV05td44PJqS8CQOX4=,tag:vBcTt0XRRwOUXPwj0bTDxQ==,type:str]
    pgp:
    -   created_at: '2021-03-16T20:27:19Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf/boVxgW/0NzQtko1/t42ZuG7nKYyYVzSnCLB9YWVDBNvj
            qSq2mOTx5q/2Czl6qXA3a3NEn9SLpruL0lOl9eZa6zObrSiEQ33hFPFla0Gxqq6O
            Oq1cbTlEKOc3jjozfvkARk+UfS71NNxMi+gwL9niSfumSbwGFXhcHaOUHZWHVR0T
            tY574FFLrxy//3YpsbPzvhNLdW5cYB2jejMRFlPrPQaEmMrbOFel4U3nJ/MJ5vyc
            R2SBnjjGTYieMccejr4lyziP37v8etQphooj5RYvyOS0fyZ9IwUn0RYf0Ho4B3Md
            wJ2/G6m/F/TRqQ6swjY3xB40nKK/swCUKbkH2w6QktJeAZv8kZhow9uMoiiEC86g
            vKn7Y4D/MEZnVLbIlH0YLoM5Q5UKeSnp2fXBALow45pBFFihAQ94DMs2L6+0ERHw
            D/7UH+7vRFrOFsOaNscnliXKjauPpB+M14mfxv8B8Q==
            =7XdW
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
