apiVersion: v1
kind: Secret
metadata:
    name: thriftserver-server-conf
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    thrift-server.conf: ENC[AES256_GCM,data:rCzKZxdJARcPCMzc2H9jRDoL/xj11l+Td4W4VfQYGf1SYs0LNr6K+hLL7lOvQ+0t9ET/rnkzGcshsu20cvYJaaWGX1YbeVJIKz+NyEE3Ij5/ceHsj2h6Co2wh06AJny3WcBD8NELIAawtByWAuvlEuFVsFBcWeWEmWiM4f7CJU62te2Lghp2aPK1V4TshWM3qNB4Qtaz8zvuA9Ay2SAEOv7gZzwGghcRrMEDxQU8QUGfYcrKVkEt9RxIHiPmI3USVnMq8YLWO0v6CCG+RjlF/dQvBdDJRf5UYD0AdjFpqs2m26AwhZ9J+NazruYALxmNnv+LsQIp8fQ0n509Ne36SsnwXp12KczIl4qiKF2B5I3nJb1bHijA3QXeijQjI07B37TjJzzS/vgXxQ57celKP3TvBVWmjsTS2AaltnNHZsKEZ9AQSDIlol281x9C6/irNHz5IRohTCH/v341Q1Fl2MspxsyZM14s3eeOtOHSam5k9AWm3bIIbyAhfSy6zCgMF3X9BCAbRLBBcP0wTwtW/PUs3OOKiu0sAxwgRCurMkcg0WWs+2yamyDv43yrsN6qNFUbDXbiqzA2VZgcmW8MfSSFmfHETE0sFklhgbRvt6Od0BcShAypw+JoD5kpYngJ2Mdgxa7KhrGNxaYGU+fmQCfXV3lidDE1xqNy7solFEi/DNWL82f45AKi2PE0sK83EHXFD7h8KG3QR2zW3aA8HUO96evevv9X3zkqW+FTCje8Iiaz4avrkkSE67QPnbX0+2WJvgC4HetjKwUl3/db+Yk9YI1XhkPaQZ30lgYrs/rA4DpHpVqn3A7jYjwfMKnW8Ik0MZmjMP6pu8QnFcEpwqy1/NEph0yP74suzGWRFegeCMaG49Iggsf/Yrc5wpOSTAgbMiHUF7kA9zF4T7C5mnLiKvwtNQeOEk1zj8T8CuDz4S4JXQOSRRl2+8TCJ1nZNIF8HN/lWhBlXmp3XBfcojc+Psh3tZcVt/euPfPJJj96Hj35fny1Iy/rz3fhVooTMaudr+KMfxyDqFjgivozDQ04l/wMc/21I9Xpf3USav1FlJi3o39P9FscUQwV8xU1pPd+9dT15wNWcxTL5C5Qn0PmSfoqJIcPA3+QGgQPzetd/aimdXHU7uAJI5xrDNbOgJKELs1Q3Dac/E6Cfq6WeewE6YJQfu1yRHOkXjf4/ODof2wintJT6eFbA7C1+f6e5c0uySEUv3PNGgKhPzxKhpkxcljDagzl4H9IzzEjDfnj5wvHBJwxn4xsM94FplQrq4bDXYGmbjObA9gL,iv:ZVGLiOcVW1YHNCHOHZgdIqIeQ62j9pJdtcgeilp/Vms=,tag:oRK/vqCOsRpMAyJPj1qk2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-10-22T11:05:20Z'
    mac: ENC[AES256_GCM,data:YFQYNQG6d8B80L/85YGTC27FanZCaJFn3LxqAa9UjcCJl9083wu+gN0UVyKV7gDCcKFMuUMw7NxzQ9qbQ5AzbcXcIAmqWkxVSKYvj1o0Zoo13zrQjFXc6MIJlyf9MAY/BtLgMOF2+nifNNZ1aPR2OpbU2kfjxJstpd+z0q/witM=,iv:LJZSZMpbQBNkyuKmSlarwi9Cr8GEGfwHUMVghaTBP2s=,tag:ylQ6N2ZUl0q2sVlmFL7axQ==,type:str]
    pgp:
    -   created_at: '2020-10-22T10:32:46Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf/TT01Hya6g6c46Eellmm7AAesl1eV2TG2fkFXwPTGeXd/
            snKO304OlAvoeLPO1FpAieSPy7L3PdKdLaP89uIa14jz0lqQbIvFuqFbe+T0ju3P
            hFJn0rM3FtUOaLUV8ewi2zuvdUhWV6q73xlzXW7on6pUQtTQkLAhdCNXksXG0T8N
            pYhLI9m9lh6O8wpwNQpxZZgSEjfGIY/yDoU6JDjAgbY4+j1gd3zzOsrthi6T+TG5
            FIw5sySI90rGCDGQ4uG/o9AN0y+FylaEdrxwK5/3IlIpysXmQIDgZZnT1TIwTMM8
            56++Ru/KxmgNDgu21u1FeAbvAu9q6fvxyMqTFiOO79JeAb3YTu/GkNOM5KIGqxmN
            DhhFISp5CGh5mtMeZIkvfb14ggBS8ghM8kFuaYev4UcMKGKcQ54+GOC9ORWJHt5P
            Max6EZOzk/CpnlnERFHzMSOI4sV7evPQ2a/extJ9rA==
            =tKi6
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
