apiVersion: v1
kind: Secret
metadata:
    name: thriftserver-server-conf
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    thrift-server.conf: ENC[AES256_GCM,data:es1qnOE/V8kMD6ndMOxoe3Xb7S6CJc/WknegVZZkY69SyI2hSlWgazW8CzkppEj6btvlyr98/5OfED5YZW8SFDY/oUFXTClslRVp1Hk0Og96d7IDAnAZFlZI0PT/2LViiNlU8zXy7dQLDYysPRnLNlaNx+gJ4txuJSNFN2PitSna21tnNlhDRZmPUG5tAU8x3BpfRwlqQHMvatp0JbZI66xnH9za530+AmROYvHr9EP7fziyTntmKf2IxlOGElJeACDf50hzqKZYladbOdd66tsu9/H0K1KX830yMJ08i+onN8s2fTag34xa4SxWSXk9jXqoQCINTtuIrY1T/1gzmiRVneJhe4+VUitNBaLKmNbqYa4naDKZ1rOljjp98kImALXvLjT7jivZHkLXxqxgaPC1bHFPvyINn/dhKNuwBPv6lBiaJ5u8loAki7qxfC+7QM+aipXbnpGqssiZUl8ND140VX6BDyZnzLqNQ/8ZIAyhmhKc1vjFynTisKNs6bijWLVEI58bSp1izAYxEp3Cm7TazrVpVU3oHgHq+d4hGG/G5aCR6iZsXknoqtwMVNH+qoNg4EdAHpv9gA/YUGpEH0THhkcVWH6/nJfHDZFZ2H0Jcy1FT8ITEwrj9iIn1rx58XFEvMRtXYv0Zo0sAagYsqJdmNzeNBzvYC0L5ykdaWkDJI4H25Z74FgD1cUknY7KErDvYvJ9L+YgZ0m5jJ/Sjo/5ax56BHuWp169gUiiGIg8PqD064NMMXm+KpZKspshZlBVgKvNiviOeMGjlIXvYs+5U/5yH91Jw/MRmRqjLEWij0cszhN6QQXhrVsrTU6+EirTvL7BVBeNOlJJeja0s2a1bRIdDK6//uiH9MCWJMwKz9OKhcYfQn5v07ja2knkzl8pjsAM7agN0XJinDGIjMtunhW9V261jAkB/c4s8gHpQuEWUPl2ddWuADtcwYZG/Mkpk+iVS91cZOllHpApH/c+aO0To8N8ETDLV45fU0mKVXDAG8IXMsQJQMcvU9QtAieUOyjDMR6eReLpRIByzB9RIpIcKMTL0JsgNZVJRu3QmEmWZC3h4g4XtzT+OmvEXooipNetv0vOcChiJcfDtnATvVFKatPtF16CebE6EGCMOdnssj4KFOo2/OqHVqMKibcoIX3+9T3QWywDHHbJ/ul9VKzg8CKe7aWxdDmrZcxk+74CX2/MerUXUhemI3EFmXWoxwl781nzKCaE4J0fbqnoAy4TzpaWTQ==,iv:TTIAJy6p2AmHx4AL9gahUNnEcJ3F4e+B6mHO9cu1eXg=,tag:l1wO/vP4wtMbg+//SJ3jUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-22T13:31:25Z'
    mac: ENC[AES256_GCM,data:jHvdRUzhRRLsBQ5oG5nlpKO6X7IDLtTlgfeDReQ1z07/vGXXeZ1lBv25dUoYAfJac+PTWIh+TqlAt04PDsl8ylggG711gYboFweba3gxHJSLatBBPA8NWfu2u0imu4IiEVwQfAqCN+KhW8VLQYZVVSKvrHI4AUZsMoSfjbROQXQ=,iv:NLxji3bNh88BfVI9ZHxGvnvufEcJ7KgHxkTcc4ntOxU=,tag:V3FpS/ahb5ONnehtl3N48g==,type:str]
    pgp:
    -   created_at: '2020-12-22T13:31:24Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf/XmO/DL2FGWSrOgKoKKKA5pzZhBhVhhhSWey4hRyXYUB5
            voayYtv1uvEtBmgI1+0jv4iHdJZCS0U8RcAx3ybD/Rql8XfeAurZspQ9QzvZBQyl
            8JDauE/W9GmwURiGoeIv12Vy9uqWOvAPvOtQx0U4RX2S9dC8gu+UBaoEsD68yQ7L
            +UvmVTQO2CM2/1KwFwiJPjot4+pzCSfYLzWVYbf7sZLRCGY3VmD38nRXDNsBzyk2
            Bw9Vl7vzzfDiE/mM/qefYQfZJgtT9dpFAY6djHgEJjCgOI8W2UdeNVEO35kTotXI
            TVPil7M/nEiZVxWTLzFeDJM3ryJS4FJ8jzu6JISOqtJeAb4TrSR9qNVLrX7AfhYh
            az+PW3EuvfTNW2iMW4Dk/1pyaJvvcApIzBQ0XZuh95ahddvy+cFR5vv6DDUCBUsX
            YVfmQpbi2PavqmW/B9fk185+q7wZRcMb5W/1G4sRFA==
            =mLho
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
