kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql
  labels:
    app: presto
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
