apiVersion: starburstdata.com/v1
kind: Presto
metadata:
  name: dev-presto
spec:
  nameOverride: "dev-presto"
  clusterDomain: cluster.local
  environment: ""
  additionalJvmConfigProperties: ""
  additionalCatalogs: {}
  additionalEtcPrestoTextFiles: {}
  additionalEtcPrestoBinaryFiles: {}
  licenseSecretName: ""
  imageNamePrefix: ""
  additionalBootstrapScriptVolume: {}
  additionalBootstrapScriptVolumes: {}
  additionalVolumes: []


  prometheus:
    additionalRules:
    - name: failed_tasks
      pattern: presto.execution<name=TaskManager><>FailedTasks.TotalCount
      type: COUNTER
    enabled: true

  service:
    name: presto-service
    type: ClusterIP


  image:
    name: starburstdata/presto:338-e.3-k8s-0.41
    pullPolicy: Always


  memory:
    nodeMemoryHeadroom: 2Gi
    xmxToTotalMemoryRatio: 0.9
    heapHeadroomPerNodeRatio: 0.3
    queryMaxMemory: 100Ti
    queryMaxTotalMemoryPerNodePoolFraction: 0.333

  coordinator:
    cpuLimit: 2
    cpuRequest: 2
    memoryAllocation: 4Gi
    nodeSelector: {}
    affinity: {}
    additionalProperties: ""

  worker:
    count: 2
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
    deploymentTerminationGracePeriodSeconds: 7200 # 2 hours
    cpuLimit: 2
    cpuRequest: 2
    memoryAllocation: 4Gi
    nodeSelector: {}
    affinity: {}
    additionalProperties: ""

  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 15

  livenessProbe:
    initialDelaySeconds: 300
    periodSeconds: 300
    failureThreshold: 1
    timeoutSeconds: 15

  spilling:
    enabled: false
    volume:
      emptyDir: {}

  usageMetrics:
    enabled: true
    usageClient:
      initialDelay: 1m
      interval: 1m

  hive:
    awsSecretName: "aws-secret"
    additionalProperties: |
      connector.name=hive-hadoop2
      hive.s3.endpoint=https://s3.upshift.redhat.com/
      hive.s3.signer-type=S3SignerType
      hive.s3.path-style-access=true
      hive.s3.staging-directory=/tmp
      hive.s3.ssl.enabled=false
      hive.s3.sse.enabled=false
      hive.allow-drop-table=true
      hive.parquet.use-column-names=true
      #hive.metastore.storage.schema.reader.impl=org.apache.hadoop.hive.metastore.SerDeStorageSchemaReader
    internalMetastore:
      cpu: 1
      image:
        imagepullPolicy: IfNotPresent
      postgreSql:
        jdbcUrl: "jdbc:postgresql://postgres.local:5432/datacatalog"
        username: "datacatalog"
        password: "datacatalog"
      s3Endpoint: https://s3.upshift.redhat.com/
      image:
        name: starburstdata/hive-metastore:k8s-0.7.osc
        pullPolicy: IfNotPresent
      memory: 4Gi
      cpu: 1
      nodeSelector: {}
      affinity: {}
