apiVersion: v1
kind: Secret
metadata:
  name: hue-ini
type: Opaque
stringData:
  hue.ini: |
    [desktop]
      # Hide unused apps
      app_blacklist=impala,security,jobbrowser,jobsub,pig,hbase,sqoop,zookeeper,spark,oozie,search
      secret_key=8pyufhgwp08erughyp8swe7ru
      http_host=0.0.0.0
      http_port=8000
      is_hue_4=true
      time_zone=America/Los_Angeles
      django_debug_mode=false
      dev=false
      database_logging=false
      send_dbug_messages=false
      http_500_debug_mode=false

      [[django_admins]]

      [[custom]]

      [[auth]]

      [[ldap]]
        [[[users]]]

        [[[groups]]]

        [[[ldap_servers]]]

      [[vcs]]

      [[database]]
        engine=django.db.backends.mysql
        host=hue-mysql.opendatahub.svc
        port=3306
        user=datacatalog
        password=datacatalog
        name=datacatalog

      [[session]]

      [[smtp]]
        host=localhost
        port=25
        user=
        password=
        tls=no

      [[kerberos]]

      [[oauth]]

      [[oidc]]

      [[metrics]]

    [notebook]
      [[interpreters]]
        [[[hive]]]
          name=Hive
          interface=hiveserver2

        [[[impala]]]
          name=Impala
          interface=hiveserver2

        [[[sparksql]]]
          name=SparkSql
          interface=hiveserver2

        [[[text]]]
          name=Text
          interface=text

        [[[markdown]]]
          name=Markdown
          interface=text

    [dashboard]
      is_enabled=true
      has_sql_enabled=true
      has_query_builder_enabled=true
      has_report_enabled=true

      [[engines]]
        [[[sql]]]
        analytics=true
        nesting=false

        [[[hive]]]
        analytics=true
        nesting=true

    [hadoop]
      [[hdfs_clusters]]
        [[[default]]]

      [[yarn_clusters]]
        [[[default]]]

    [beeswax]
      hive_server_host=thriftserver.opendatahub.svc
      hive_server_port=10000
      auth_username=hue
      auth_password=password
      hive_conf_dir=/etc/hive/conf
      server_conn_timeout=200

      [[ssl]]

    [metastore]
      enable_new_create_table=true
      force_hs2_metadata=false

    [impala]
      [[ssl]]

    [spark]

    [oozie]

    [filebrowser]

    [pig]

    [sqoop]

    [proxy]

    [hbase]

    [search]

    [libsolr]

    [indexer]

    [jobsub]

    [jobbrowser]

    [security]

    [zookeeper]
      [[clusters]]
        [[[default]]]

    [useradmin]
      [[password_policy]]

    [liboozie]
      oozie_url=

    [aws]
      [[aws_accounts]]
        [[[default]]]
          access_key_id=""
          secret_access_key=""
          host=""
          is_secure=true
          calling_format=boto.s3.connection.OrdinaryCallingFormat
          allow_environment_credentials=true
          region=""

    [libsentry]

    [libzookeeper]

    [librdbms]
      [[databases]]

    [libsaml]

    [libopenid]

    [liboauth]

    [kafka]
      [[kafka]]

    [metadata]
      [[optimizer]]
      [[navigator]]
