apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: hue-mysql
  labels:
    app: hue
  annotations:
    template.alpha.openshift.io/wait-for-ready: "true"
spec:
  strategy:
    type: Recreate
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - mysql
        from:
          kind: ImageStreamTag
    - type: ConfigChange
  replicas: 1
  selector:
    deploymentconfig: hue-mysql
  template:
    metadata:
      labels:
        deploymentconfig: hue-mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - "-i"
                - "-c"
                - >-
                  MYSQL_PWD=$MYSQL_PASSWORD mysql -h 127.0.0.1 -u $MYSQL_USER -D
                  $MYSQL_DATABASE -e 'SELECT 1'
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: "hue-mysql-secret"
                  key: database-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "hue-mysql-secret"
                  key: database-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: "hue-mysql-secret"
                  key: database-name
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "hue-mysql-secret"
                  key: database-root-password
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
          volumeMounts:
            - name: "mysql"
              mountPath: "/var/lib/mysql/data"
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          capabilities: {}
          securityContext:
            capabilities: {}
            privileged: false
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: mysql
      restartPolicy: Always
      dnsPolicy: ClusterFirst
