apiVersion: v1
kind: Service
metadata:
  name: hue
  labels:
    app: hue
spec:
  selector:
    app: hue
    deploymentconfig: hue
  ports:
    - name: 8000-tcp
      port: 8000
      protocol: TCP
      targetPort: 8000
