apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hive-site-xml-secret.yaml
  - hue-db-init-job.yaml
  - hue-dc.yaml
  - hue-ini-secret.yaml
  - hue-mysql-dc.yaml
  - hue-mysql-pvc.yaml
  - hue-mysql-secret.yaml
  - hue-mysql-service.yaml
  - hue-mysqld-exporter-secret.yaml
  - hue-route.yaml
  - hue-secret.yaml
  - hue-service.yaml

images:
  - name: hue
    newName: shgriffi/hue
    newTag: test
  - name: mysql
    newName: openshift/mysql
    newTag: "5.7"
  - name: mysqld-exporter
    newName: prom/mysqld-exporter

patchesJson6902:
  - patch: |-
      - op: add
        path: /spec/triggers/0/imageChangeParams/from/name
        value: mysql:5.7
      - op: add
        path: /spec/triggers/0/imageChangeParams/from/namespace
        value: openshift
    target:
      kind: DeploymentConfig
      name: hue-mysql
      version: v1
