apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- thriftserver.yaml
- hue.yaml

commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: data-catalog

configMapGenerator:
- name: parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: jupyterhub-cfg
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
- name: storage_class
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.storage_class
- name: s3_endpoint_url
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.s3_endpoint_url
configurations:
- params.yaml
