apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    annotations:
        template.openshift.io/expose-username: '{.data[''database-user'']}'
        template.openshift.io/expose-password: '{.data[''database-password'']}'
        template.openshift.io/expose-database_name: '{.data[''database-name'']}'
        kustomize.config.k8s.io/behavior: replace
stringData:
    database-user: ENC[AES256_GCM,data:Py3rgOPgxssteNs=,iv:VInTTER5M8AYmxIYk79hSw2+8soNBiyI7ayklh+KC9g=,tag:mHjg8CXD8GCRYDomO8Q3Vg==,type:str]
    database-password: ENC[AES256_GCM,data:qrXxqzj4IPUBuTfASZYF0t4AQTn1odwO,iv:5dVR3n2YR+HlDiKPRuSa+wKyXqfq8bg/uQk5Xxod5CM=,tag:VeC+5GIPD7s2SzuUHEsylA==,type:str]
    database-name: ENC[AES256_GCM,data:diCwRNQy3ajXecQ=,iv:K8cBbn4Ve/WBEEJKqNmxDWLmBjBtWfUlXBkX+T4z8hE=,tag:9RrD38lF/4NMTZXp3YBPBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-10-22T11:07:25Z'
    mac: ENC[AES256_GCM,data:9TNB6Mh+QhMJUA62zoJc6VfMaqC0Puc70kYQb1kwcLWUbVmbVcxid5u3JeLTnZZEi1/3KI7B5RdD8ulQKiZpkAuWCaQnNLFuaj4zXWo3uU+vAuMQ+d43egBmGA2ZYkwuZfkOSH+LL3k9nMy1BS4HUYJyJY8NgDJc8oF0v2dQS+Y=,iv:s8AdxfFsH9rNptduSziRCxtLDPGplH1dpnyFhqvMQ3w=,tag:7HIV8JS2e9dSJW5/lClvqg==,type:str]
    pgp:
    -   created_at: '2020-10-22T10:32:12Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf/b4ZLQqacsK9ET06iwg91KBiJ86qG6qjT0z5ueMf6OttZ
            6HqE28+BsIG8O0didjYGU7qEaaD0o1Cqe0tVJJn+Vb7RIG8iQgketrqujLUbPl8J
            8m2mYDLCuAI2WCLosQc/r2iWlMbBQebCo2ko62dvhVekhU4Tpd8USjaLyMd1D94w
            soEoRtnl4yhlNUn77Zw7zf+eLghVmSGOKqNopvZUt7FeSLsdh64iSKM/H13nJ0E+
            4UUYzAhuESejdL7beaYbTICo40ySkJGKNL0CmK/5eQpI2cXEoNFQ3TVEoTvByq9H
            ZJtlh4+hJ84W3Fjs2bmPLnZrNR7tatRAgQFk7pS4S9JeAaxURAJgiFEltorit2N2
            zGs/+p3gI8MTptLDEbwysTxNHU9Pz3cpFKATf80IfMS+iNZijzPyIdlqk0fUFu/Z
            JjFE79WfRKJHu1iBF4fudbfr2A5FMvp7WRcAbUgafQ==
            =b8Hc
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
