apiVersion: v1
kind: Secret
metadata:
    name: hue-mysql-secret
    annotations:
        template.openshift.io/expose-username: '{.data[''database-user'']}'
        template.openshift.io/expose-password: '{.data[''database-password'']}'
        template.openshift.io/expose-database_name: '{.data[''database-name'']}'
        template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
        kustomize.config.k8s.io/behavior: replace
stringData:
    database-user: ENC[AES256_GCM,data:ySJjpaW+n0zkQpY=,iv:rqP5OGEci76Rg8Xz+PEWQo1rh/PzZ66mM3eicJQGDCs=,tag:UzLsTLK8Hf+hS7r9NlocLA==,type:str]
    database-password: ENC[AES256_GCM,data:Vm2aOydUxj6Kk78=,iv:1g9AY1h2gtejTXZdx2DdQRnIVyuCPZOhyWyIQZQK5h0=,tag:SZ3xbY5bKFK3BDStgyLVoA==,type:str]
    database-name: ENC[AES256_GCM,data:3a3a6J5BAoUWRBc=,iv:pbzyGyYHwpmUn0G4qSPpB2nyvJV2Ks/fXbYqCrgGg5g=,tag:TSJPpiz6akBW+FT4XYsiKQ==,type:str]
    database-root-password: ENC[AES256_GCM,data:SVH1eA==,iv:gwDOP8l0VaqL7DhYzq6GbyHYSTDNoPwlNSOIAfbRPa0=,tag:yDlqGxAsMLaHF2H5+Rabjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-10-21T14:56:03Z'
    mac: ENC[AES256_GCM,data:WYefK0MuXV3+/9MuMVtNCTAg3xEuJq4CD8urPvgDrSxmU/c79mY1snA0pNAlf3JVVqj+GPHzHzBft6w4NlboQfKNI2AWbDEaHtoA3gR4Zh9x3QRrxpEDw+8UD1vjMTHU87iTo1k2BMWj3pjbjAdtSNi7hiiB4tzjcbphVGw6Afc=,iv:ZAhKAM9UH1Dy1gmg1XTIWI5nTGI7ZsD/pt5OQZMAXb0=,tag:clk6ezet0sRZ9slnqsQuaQ==,type:str]
    pgp:
    -   created_at: '2020-10-21T14:31:34Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf/bnxYHi0zKtRHrTeHDwMkCHP3NAQpnDX7qHMKnmHzU6qU
            y4r80uTaWujets20tbAJ9R1W3MASuavnE0IQxhpCgozjRzkRdJlMVWS/0lk41KLM
            s4QjsyiQ1XUzOn12cYlMI/RIZBuBdX4mTIPqjT2jyh7zFzl1mUDPPNh31In5kqDU
            xonAlCvgYA+OIJhkYVw191ptX7CMboSyi/V5lpYP9wGc8AYaEUseQ2dgUfxFTEcQ
            /K9alH+UuV0dpFfxvpBQDMbeXHRbXA4JzCrYEu+WhVCRsgz1eW0k2yOhXo2YbCou
            KDr+gpK4chY6F2i5NDwCoy5DPvwgvrPDuyNHY9HGE9JcAZSf1gucivGGrSlL1vyD
            LuJ0hvb2+/5Ig5IRKjZTj3oNdwXa1wkpktyOhR6ZLGjfnRO1G8R+XRq3i37HfPPl
            RsuoD6HKosSnCRn/DJ/zm+vEauOxOyyy7WrMZpU=
            =9Qwq
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
