apiVersion: v1
kind: Secret
metadata:
    name: prod-aws-secret
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:a5XnVIyp6ekZPPiL6Tr4W1P+wK0=,iv:rWcnxRuylkbbTnU68eyJmJcdUtxx0vbhqwSA5u/gb2M=,tag:PjG6nvaWkJk5sl2ABb4CTQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Wky+8NOq2UQHUjD+MVXHA2okWaz/u3kgrOrmn7QS7GTUeVWBmVqOtw==,iv:AvvachF/bDV2cCchdaPjB6XinGfOSZtb6JJ1RI/URt0=,tag:vmhZQ/7krjLpRKafYn2mXw==,type:str]
    BUCKET: ENC[AES256_GCM,data:OhYq+RGC/PP2fg==,iv:Ys2tQhZWG1za1x+dZH907YjwDQMr3AN66BlnOGOIGIQ=,tag:YUC5OW8wDWDyTcw01sDJqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-04-15T16:02:20Z'
    mac: ENC[AES256_GCM,data:T6I2KjgMbuxYztD8lbxQyd1DN3b2Zwlfajz4h0vZ8KqYo6qgfp0lRduWVdhnpSkjuiaGzzi60O3TJ7+Cb/ZbR9KiByALibrtYSYXOmeTejUC1RbnVvJkVXoCpZfI52XCoUN66FHpesnN+eBCGUKwUNTfWWhyLc4flaQ4Wi5nIO4=,iv:uP4W7NO/cDNBZKA2rBolu3p3o2vRwh5U4xQCsYQKAJc=,tag:2ctmUuj+260RPtEtLCyL8Q==,type:str]
    pgp:
    -   created_at: '2021-03-17T20:36:31Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf+Ibgj4lx9lxeBMZQxl5MfJMOc3d2th2AJAk7Sw2QXO0ix
            fAz7VkNtLSevhfy4pLds7Dac2OiDV8N6FnI0r8DKK64NLt/t0xMNbFmtS1bJJZK1
            FGag5qUTq3TGYATsg89E3PQwzLXtxCOmlsOfhyS94CdATGsE6QSRQV4GQ9c9YGa6
            PgGtdUClVMDJef8Z5h4SU219pv1RDKLa4yJcyXw90cNL4/YhMjbnnxd72lfnbP9D
            9v2LmrOW/U2swJlLsGzgs/24STIcD9NYdOHIcnnJWMbl0goDOjg626c+SUQtMUBT
            70WzoyV6QMi9SrcvuO4+QO8n6lbL03UVZ9AGlb9VjNJeAXoyjvHHosmM19LL2d+O
            YCO5RY4swLSfZiSxX4X5y0ybi0RoJw+vW4QkGq29k3JNLUKtcoHga1pF6l0noV0e
            GgY4dHoRHscYY0SmZDYYESVNT0k8NEEF/XgmXiOt8A==
            =9KNE
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
