apiVersion: v1
kind: Secret
metadata:
    name: prod-aws-secret
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:VXx1/biH8CfEBHfaTt4Rf5H5HIw=,iv:GADPlT771SMlzfbCInQFPyHD2cQiGCc+h38spPo2k8Y=,tag:E3o7GHkpxI+MSuiM6+0sdQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:USu3wbzfEuUR1L3GUBVyrPFjJeT3KSPVwMBZm6H25JT64raUzxF1tQ==,iv:7mKZYBQbi2Xiht5WIkf9W+RU3/Xn12zaUiDUeaSD6Lo=,tag:pRsX6e7gp4ecsAUQ4SPSDg==,type:str]
    BUCKET: ENC[AES256_GCM,data:YWEYYpiT/AEX0LRKNaZw5If5TBhwGNlnXnc=,iv:fM7jzRFgGnal1RpHJsDDNx/lbDYe8DK91HzHuTWHkcg=,tag:OYNaQj/gLoJl9ERAklhfnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-04-16T21:15:09Z'
    mac: ENC[AES256_GCM,data:Y8EbedEri6K/71RbieK6WlatuDE4d43W1TIG80N7w+B169bmKhPK82/fan+IBOLlkYK9zi7T32vv8G9CT98qfckeQbm7QfJP9UmmRR72ht3ZJGjAEhYz9WrxsrlzHxVbPvuBE948I1nfvMMrgPWbhrrfiKCBlS4455f6g1P5mFU=,iv:bEEeaP9r1+gxyS9J6DKkDZ+CVPDG0R6iLiirrErz8Ew=,tag:L/Pw4YKAZeqC07l2tcLeFg==,type:str]
    pgp:
    -   created_at: '2021-03-17T20:36:31Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf+Ibgj4lx9lxeBMZQxl5MfJMOc3d2th2AJAk7Sw2QXO0ix
            fAz7VkNtLSevhfy4pLds7Dac2OiDV8N6FnI0r8DKK64NLt/t0xMNbFmtS1bJJZK1
            FGag5qUTq3TGYATsg89E3PQwzLXtxCOmlsOfhyS94CdATGsE6QSRQV4GQ9c9YGa6
            PgGtdUClVMDJef8Z5h4SU219pv1RDKLa4yJcyXw90cNL4/YhMjbnnxd72lfnbP9D
            9v2LmrOW/U2swJlLsGzgs/24STIcD9NYdOHIcnnJWMbl0goDOjg626c+SUQtMUBT
            70WzoyV6QMi9SrcvuO4+QO8n6lbL03UVZ9AGlb9VjNJeAXoyjvHHosmM19LL2d+O
            YCO5RY4swLSfZiSxX4X5y0ybi0RoJw+vW4QkGq29k3JNLUKtcoHga1pF6l0noV0e
            GgY4dHoRHscYY0SmZDYYESVNT0k8NEEF/XgmXiOt8A==
            =9KNE
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
