kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: trino-db-volume
  labels:
    app: trino
  annotations:
    volume.beta.kubernetes.io/storage-class: "standard"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
