apiVersion: v1
kind: Secret
metadata:
    name: prod-trino-db-secret
    labels:
        app: trino
    annotations:
        template.openshift.io/expose-username: '{.data[''database-user'']}'
        template.openshift.io/expose-password: '{.data[''database-password'']}'
stringData:
    database-user: ENC[AES256_GCM,data:JxwE/AE=,iv:O8ZKBVYgbWIGLt4yQ/uw3EI+4dH5fXRUNegU20MjS/c=,tag:tJYo+NqWkWbVDYzcz+vUbg==,type:str]
    database-password: ENC[AES256_GCM,data:hRC1+VxFiUTr3g1mQlE6uw==,iv:nOlgKBmWv8FzZUyVY3mZasxD4kLQ1yJrcaCPsaqC3P0=,tag:CXXvCBBsjn92lCwZ75hoXA==,type:str]
    database-name: ENC[AES256_GCM,data:WgVMRYA=,iv:3Nm5Z255UYEdpd2sWBu8yaWR2aAHgKySgEGOl7JesnE=,tag:RnmfJ8SIFcKrJsoKoEceeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-04-14T22:23:18Z'
    mac: ENC[AES256_GCM,data:lpLnjN96Q0Ny5LEszCV9xB8aWm5197ExW7trPpzdxm0pznFIKjvXzBtYWEaRg7iwMXeQt+nY6zSbfFGM0qV/ZvfCLgJUOqoKkZPNS3ELkRdx05cBrJu5E1ZVkSd2EdtvOHSkFsuZw7RVoSpTVdPfCAYUOZbZH9RDqiVkZnOgviM=,iv:dDKMsPigZf7IiBsucaa6VEHt1G94c1U2J05DpFQ9/0w=,tag:IwS0WTfwMALgb7/p4KOmJg==,type:str]
    pgp:
    -   created_at: '2021-04-14T22:16:47Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf+KrLKbbA3xZTlbhwNHYnrQ5ExaoVFyeh9uun1RyhdU6Hj
            h2+6uTyHK/4oJWn9w9vwkGlSoZg9NsODOjtxrhXj1hyWYp5YJtDRl1JNcK8RUbnY
            vOZhz9SuxNVby4PQgDpO/2qYvz3tHb3IzwdDpztBrNs1CMvRrFMocIANNpskSt+4
            sQYLJaoYXcA5acD4IOxWhO1omNN8LqZGRhJEs4FIT+7MFnhwuLLnx4UgEUvd9jDS
            QdiQKDzMQyxVlVt3LG0aAu7dXlOi/0ZfZONbhb/gVArmwaphWDc1iHROQt3EESPQ
            7FVCG44dLqpGsZTc6gC5D8ksKW4D1upiyTQWB0T6c9JeAdqbDE+ojYL4uRd254fS
            RNWm56wX1oFZiXMGiANnP6oNsKV0nVgDIz/QEjUDmThqjBOF8IUT/wMwYUa3ClQM
            2wueG3+JMByzJzD+UDsPmKbAjFrP++AsH6Q6FBpf1w==
            =dZv3
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
