apiVersion: v1
kind: Secret
metadata:
    name: dev-aws-secret
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:yr69j//P11/besahH63Ep+NIg1w=,iv:Z8uIMW41iM/8IDVOXMQR0et3e27J7JfC5FxXaFWKKcQ=,tag:/6jG2QIxAMrTTwh2+OAVsA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:571i0uXGckZI8QaXzoO4tWqJsnYjCLdD6HkthKYKm+vmNLXu5owobg==,iv:SKLODWw42lEEDnK8lqxBNsI1gw3uVr7yexx/JHOxxsc=,tag:qwqCAaxv6cI+tVfW3rb1jQ==,type:str]
    BUCKET: ENC[AES256_GCM,data:zvyyVFJFs1Omgg==,iv:lfNSUyXZqjsxD79m2XRDqr/1NAbVmwYSG1HsNwgK6og=,tag:bCUvv2JRszJoRzy6iHT7ZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-04-14T21:52:04Z'
    mac: ENC[AES256_GCM,data:jVpSJn11ijEp/RJUy9OPKK9HQWsVdNaP076MABWTBmc7ryuaqRJKI59m1ouldJF9BJClXFlg7bBON3+Nl070+33P+4HZ63quysP7eL6HLDTJNLFDtisHzg02uf/N/bbwvwCi2EFONkYOvUuMa9bbU6EFFNb3ykM8SstklhYfcWo=,iv:W0ZZUJCIJmu5nKtU+WBy1NqIbKwc/6HLFxbl6z5qpxg=,tag:ENrKYetjbOf/M4d7xMNXfQ==,type:str]
    pgp:
    -   created_at: '2021-03-19T17:54:20Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf/a8O7677b+yvttESYH+3t2fep10pUui3U3iwaSSqUO3gx
            XkCA61xuMA2lvh6nlABjk43qqvM9hNRSQ3ZWoPFgDf5yzDVq3cpMr3rXYM/EbObX
            4lSKOSTwG0mf0lOomCEHOcbrT/3YnHyXcjRCyrmghmnB00Y4zARF3TYVDbhIZ+2+
            xvdwcgVNGZioXQtH3hWwq5wu9Kmx6Qr1MepzrdqaRJSd7rQYyYCCa9k/l1g10E2N
            Ks8tMCNs9YwaHPiIafOHrwhgJPLrvSPnvM6W28+OKHByeAxoGP6v8gBnM1DtDM4l
            9298rp4JW5NQYzAVewOmq6BZAc33oER8bhC3N45yDdJcAS4Ut8EpEqzdZWg18zEa
            iO+3wRDanXFSDn6C60R6GzQ/dQ+vIx3K8qx0vY2flmRnboSZ++6MTi6p2qxiRXf1
            ro355e/pvCOpjEGdp3nte6briOveDXiJOs0A/JU=
            =swiE
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
