---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: rsyslog-ingest
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: rsyslog
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKER
              value: "dev-kafka.dh-dev-message-bus.svc.cluster.local"
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - mountPath: /etc/rsyslog.d
              name: rsyslog-d
              readOnly: true
            - mountPath: /etc/kafka/certs/
              name: kafka-cert
              readOnly: true
