namespace: dh-psi-monitoring
resources:
- ../../bases/prometheus
- ../../bases/grafana
- ../../bases/alertmanager
- ../../bases/oauth_client
patchesStrategicMerge:
  - prometheus.yaml
generators:
- secret-generator.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: additional-scrape-configs
    files:
      - configs/additional-scrape-configs.yaml
