namespace: dh-prod-superset
AUTH_USER_REG_ROLE : Datahub
STORAGE_CLASS_NAME: 'ceph-dyn-datahub-prod-psi'
SUPERSET_CPU_REQUEST: '1'
SUPERSET_MEMORY_REQUEST: '1Gi'
SUPERSET_CPU_LIMIT: '2'
SUPERSET_MEMORY_LIMIT: '2Gi'
POSTGRES_CPU_REQUEST: '1'
POSTGRES_MEMORY_REQUEST: '1Gi'
POSTGRES_CPU_LIMIT: '2'
POSTGRES_MEMORY_LIMIT: '2Gi'
