apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter
  labels:
    app: thriftserver
stringData:
  DATA_SOURCE_NAME: "postgresql://datacatalog:datacatalog@localhost:5432/datacatalog?sslmode=disable"
