namespace: dh-stage-superset
AUTH_USER_REG_ROLE : Datahub
STORAGE_CLASS_NAME: 'ceph-dyn-data-hub-stage'
SUPERSET_CPU_REQUEST: '500m'
SUPERSET_MEMORY_REQUEST: '512Mi'
SUPERSET_CPU_LIMIT: '1'
SUPERSET_MEMORY_LIMIT: '1Gi'
POSTGRES_CPU_REQUEST: '500m'
POSTGRES_MEMORY_REQUEST: '512Mi'
POSTGRES_CPU_LIMIT: '1'
POSTGRES_MEMORY_LIMIT: '512Mi'
