apiVersion: v1
kind: Secret
metadata:
    name: stage-aws-secret
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:zNmyZTFye9C8XYsPgZSzTGN1RfM=,iv:DgftDCb5gY9fMhLrJe7ANA9o7US3Fr5mRUnZf8tmaIM=,tag:7f2Z45Sei9EVZsSce7InXA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Y9w1p91S1egOHI2oyRNEnkmkKHOhSYlQrmKZNrbxcctm4JdpPJK4zw==,iv:OJBehMY0mqzPw0z7EpVUJ/4OAEAZyVpq2zlmxbkpWJQ=,tag:Y9o/z7THyWsDW9VA3Z+nNQ==,type:str]
    BUCKET: ENC[AES256_GCM,data:SmvdzxLSEthbQRfRvhlZ2J/AvCfSUp55HEw=,iv:BRTCXtqTRoVcLLhXymHXXi/UqAm2mVF6XG2Up9ErEHk=,tag:A39UEuZ/2FXV1AibXvvFZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-05-11T20:25:09Z'
    mac: ENC[AES256_GCM,data:1FRxzmtanreYub9byl090o2afDGpER5yCrobyGq4E0l6L5PXG/8CZl5JR6bHkTEB4UPT5vkwx0TehE1Y+k4saWS5tUv7zb7O2C2+NNxpENPFSl4mqaWU+ePXyfVjgf6Oixs/AZjG63+65QhamPEX9mrcEEHgQ5/LvHTw+yCCkWc=,iv:H6cl7uvJONGBMlCCDisr/W7xU8yBKdJT932ECkRU5to=,tag:F8WCTuPl86Qkl4MjVY2IAw==,type:str]
    pgp:
    -   created_at: '2021-03-17T20:36:31Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf+Ibgj4lx9lxeBMZQxl5MfJMOc3d2th2AJAk7Sw2QXO0ix
            fAz7VkNtLSevhfy4pLds7Dac2OiDV8N6FnI0r8DKK64NLt/t0xMNbFmtS1bJJZK1
            FGag5qUTq3TGYATsg89E3PQwzLXtxCOmlsOfhyS94CdATGsE6QSRQV4GQ9c9YGa6
            PgGtdUClVMDJef8Z5h4SU219pv1RDKLa4yJcyXw90cNL4/YhMjbnnxd72lfnbP9D
            9v2LmrOW/U2swJlLsGzgs/24STIcD9NYdOHIcnnJWMbl0goDOjg626c+SUQtMUBT
            70WzoyV6QMi9SrcvuO4+QO8n6lbL03UVZ9AGlb9VjNJeAXoyjvHHosmM19LL2d+O
            YCO5RY4swLSfZiSxX4X5y0ybi0RoJw+vW4QkGq29k3JNLUKtcoHga1pF6l0noV0e
            GgY4dHoRHscYY0SmZDYYESVNT0k8NEEF/XgmXiOt8A==
            =9KNE
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
