---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: "dh-stage-trino"

generators:
- ./secret-generator.yaml

patchesStrategicMerge:
- ./trino-db-pvc.yaml
- ./trino-config-secret.yaml
- ./trino-coordinator-dc.yaml

patchesJson6902:
  - patch: |
      - op: replace
        path: /data/s3_credentials_secret
        value: stage-aws-secret
    target:
      kind: ConfigMap
      name: trino-config
      version: v1
  - patch: |
      - op: replace
        path: /data/s3_endpoint_url
        value: https://s3.upshift.redhat.com/
    target:
      kind: ConfigMap
      name: trino-config
      version: v1
  - patch: |
      - op: replace
        path: /data/trino_environment
        value: stage
    target:
      kind: ConfigMap
      name: trino-config
      version: v1
