---
apiVersion: v1
kind: Secret
metadata:
  name: trino-config
stringData:
  config-coordinator.properties: |-
    coordinator=true
    node-scheduler.include-coordinator=false
    http-server.http.port=8080
    discovery-server.enabled=true
    discovery.uri=http://localhost:8080
    http-server.authentication.type=PASSWORD
    http-server.process-forwarded=true
  password-authenticator.properties: |-
    password-authenticator.name=ldap
    ldap.url=ldaps://ldap.corp.redhat.com
    ldap.ssl-trust-certificate=/etc/trino/certs/RH-IT-Root-CA.crt
    ldap.user-bind-pattern=uid=${USER},ou=Users,dc=redhat,dc=com
