---
apiVersion: v1
kind: Secret
metadata:
  name: trino-config
stringData:
  config-coordinator.properties: |-
    coordinator=true
    node-scheduler.include-coordinator=false
    http-server.http.port=8080
    discovery-server.enabled=true
    discovery.uri=http://localhost:8080
    http-server.authentication.type=PASSWORD
    http-server.process-forwarded=true
  password-authenticator.properties: |-
    password-authenticator.name=ldap
    ldap.url=ldaps://ldap.corp.redhat.com
    ldap.ssl-trust-certificate=/etc/trino/certs/RH-IT-Root-CA.crt
    ldap.user-bind-pattern=uid=${USER},ou=Users,dc=redhat,dc=com
  group-provider.properties: |-
    group-provider.name=file
    file.group-file=/etc/trino/group-mapping.properties
  group-mapping.properties: |-
    data-hub-admins:rmartine,acorvin,aasthana,gfrasca,mshah
    ccx:mbacovsk,tsedlace,afalossi,mklika,tdosek,ometelka
  access-control.properties: |- 
    access-control.name=file
    security.config-file=/etc/trino/rules.json
  rules.json: |-
    {
      "catalogs": [
        {
          "group": "data-hub-admins",
          "allow": "all"
        },
        {
          "group": "ccx",
          "allow": "read-only"
        },
        {
          "allow": "none"
        }
      ],
      "schemas": [
        {
          "group": "data-hub-admins",
          "owner": true
        },
        {
          "group": "ccx",
          "schema": "telemetry",
          "owner": true
        },
        {
          "owner": false
        }
      ],
      "tables": [
        {
          "group": "data-hub-admins",
          "privileges": ["SELECT", "INSERT", "DELETE", "OWNERSHIP", "GRANT_SELECT"]
        },
        {
          "group": "ccx",
          "schema": "telemetry",
          "privileges": ["SELECT"]
        },
        {
          "privileges": []
        }
      ]
    }
