apiVersion: v1
kind: Secret
metadata:
    name: hue-mysql-secret
    annotations:
        template.openshift.io/expose-username: '{.data[''database-user'']}'
        template.openshift.io/expose-password: '{.data[''database-password'']}'
        template.openshift.io/expose-database_name: '{.data[''database-name'']}'
        template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
        kustomize.config.k8s.io/behavior: replace
stringData:
    database-user: ENC[AES256_GCM,data:XSKuNrpDU61YYVA=,iv:7q2mAQy3VFIinzP0AoL/BFWwP2obKUyW81pOOVPNHVw=,tag:Mtnl2ErJ05YXp6j5lthXCA==,type:str]
    database-password: ENC[AES256_GCM,data:NnU6eYSNvuuOonlq16eCE9Gto59oy2y6,iv:xbnOXm/RNkz97YVjFQ9KGJh3OUJm9HiZ3CJ4AM2KTlg=,tag:KxmQAJ3d7/Jhi+FUeII1dg==,type:str]
    database-name: ENC[AES256_GCM,data:3a3a6J5BAoUWRBc=,iv:pbzyGyYHwpmUn0G4qSPpB2nyvJV2Ks/fXbYqCrgGg5g=,tag:TSJPpiz6akBW+FT4XYsiKQ==,type:str]
    database-root-password: ENC[AES256_GCM,data:3UM1nz86ZixyfX+cPYy0yXDu2p/sTAzb,iv:/iKUQG8DETIueSpajqzaxlFOrw7BBB06suMBQKg8oiY=,tag:1BPQv9+eL7Upzm+QpX31yA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-10-21T16:19:17Z'
    mac: ENC[AES256_GCM,data:k+lgT5Q1FSCB/IrdhO8+f9t3ByRbgOds0lNy3fzR6eHBuMnEU533Rxb+d/r67WwSwr1AJs3TzIEzBqawZmjheVXXj7jDvLkdGbXx8budAntINZASNsD5x0haqaDP3yFB+JgXqyS8oyrZm+/ZM2o/0ZqjrSH4WgKaERRYqcI/XdU=,iv:C05ODSzT2Er4Nc4VlHCx1GET6CpeOaxERU2XNRHJ/5w=,tag:vs+Hlor6PWfbvIR+VW39Fw==,type:str]
    pgp:
    -   created_at: '2020-10-21T14:31:34Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf/bnxYHi0zKtRHrTeHDwMkCHP3NAQpnDX7qHMKnmHzU6qU
            y4r80uTaWujets20tbAJ9R1W3MASuavnE0IQxhpCgozjRzkRdJlMVWS/0lk41KLM
            s4QjsyiQ1XUzOn12cYlMI/RIZBuBdX4mTIPqjT2jyh7zFzl1mUDPPNh31In5kqDU
            xonAlCvgYA+OIJhkYVw191ptX7CMboSyi/V5lpYP9wGc8AYaEUseQ2dgUfxFTEcQ
            /K9alH+UuV0dpFfxvpBQDMbeXHRbXA4JzCrYEu+WhVCRsgz1eW0k2yOhXo2YbCou
            KDr+gpK4chY6F2i5NDwCoy5DPvwgvrPDuyNHY9HGE9JcAZSf1gucivGGrSlL1vyD
            LuJ0hvb2+/5Ig5IRKjZTj3oNdwXa1wkpktyOhR6ZLGjfnRO1G8R+XRq3i37HfPPl
            RsuoD6HKosSnCRn/DJ/zm+vEauOxOyyy7WrMZpU=
            =9Qwq
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
