apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-aicoe-argocd
  namespace: aicoe-argocd
  labels:
    prometheus: dh-prometheus
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/purpose: aicoe-cd-metrics
