apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/hue

generators:
  - secret-generator.yaml

patchesStrategicMerge:
  - hue-mysql-pvc.yaml

patchesJson6902:
  - target:
      kind: DeploymentConfig
      name: hue
      version: v1
      group: apps.openshift.io
    path: ./hue_dc_patch.json
