apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/hue

generators:
  - secret-generator.yaml

patchesStrategicMerge:
  - hue-mysql-pvc.yaml
  - hue-dc.yaml
