apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/thriftserver

generators:
  - secret-generator.yaml

patchesStrategicMerge:
  - postgres-pvc.yaml
  - thriftserver-pvc.yaml
