apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-user
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - cronworkflows
      - cronworkflows/finalizers
      - workflows
      - workflows/finalizers
      - workfloweventbindings
      - workflowtemplates
      - workflowtemplates/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
