apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./argo-user-role.yaml
  - ./default-sa-role.yaml
  - ./default-sa-rolebinding.yaml
  - ./argo-server-route.yaml
  - ./workflow-controller-metrics-route.yaml
  - github.com/argoproj/argo/manifests/namespace-install?ref=v2.12.3
  - https://raw.githubusercontent.com/argoproj/argo/v2.12.3/manifests/cluster-install/workflow-controller-rbac/workflow-aggregate-roles.yaml

images:
  - name: argoproj/argocli
    newName: quay.io/opendatahub/argocli
    newTag: v2.12.3
  - name: argoproj/workflow-controller
    newName: quay.io/opendatahub/workflow-controller
    newTag: v2.12.3

patchesJson6902:
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/args/3
        value: quay.io/opendatahub/argoexec:v2.12.3
    target:
      group: apps
      kind: Deployment
      name: workflow-controller
      version: v1

patchesStrategicMerge:
  - ./workflow-controller-configmap.yaml
